name: Mirror to Forgejo

on: [push, delete, create]

concurrency:
  group: git-mirror

jobs:
  to_forgejo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Holt die gesamte Git-Historie (wichtig für Mirrors)

      - name: Push to Forgejo Server
        run: |
          # Baut die URL mit integrierten Secrets, um die Passworteingabe zu umgehen
          git push --prune --force "https://${{ secrets.FORGEJO_USER }}:${{ secrets.FORGEJO_PASSWORD }}@git.24wt.de/${{ github.repository }}.git" "+refs/heads/*:refs/heads/*" "+refs/tags/*:refs/tags/*"
